######################################################################
# Automatically generated by qmake (2.00a) Thu Aug 3 23:11:55 2006
######################################################################

TEMPLATE = app
TARGET = youfs 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += connectionwidget.h
SOURCES += connectionwidget.cpp main.cpp
