######################################################################
# Automatically generated by qmake (2.00a) Thu Aug 3 23:11:55 2006
######################################################################

TEMPLATE = app
TARGET = youfs 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += connectionwidget.h clientthread.h
SOURCES += connectionwidget.cpp clientthread.cpp main.cpp
